# Generated by Django 4.1 on 2023-04-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPARQLRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='SPARQL Request')),
            ],
            options={
                'verbose_name': 'SPARQLRequest',
                'verbose_name_plural': 'SPARQLRequests',
            },
        ),
    ]
